### ISSUE TITLE
Backend API: Category & Page

### ISSUE THREAD

**Issue by mrgwilliam** [Unit-Forge/Renegade#13]
- [x] Category Controller  
- [x] Category Repository
- [x] Category Tests  
- [x] Category Model (refer to Rank model notice fillable and dates)  
- [x] Page Controller  
- [x] Page Repository
- [x] Page Tests  
- [x] Page Model 

I would reference my implementation of the Rank on the current master branch 

Namespace wise I am thinking
```
Site\Category(Controller, Repository)
Site\Page
```

**Comment by jen-dooley** [comment]
All Done 😄
